#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: "{build}"
image: Previous Visual Studio 2022
configuration: Release
environment:
  GITHUB_TOKEN:
    secure: ZRmWQTJF0B2l6J9HqJ0wjN7Rcupd0lNnGHGrXWV/DABnCwgHNttcIB6hK+XhFKwd
  NUGET_TOKEN:
    secure: 98IgrlPZtuTVTyHn7qGwmzNkhUOZ6KVUmRaZxXUPO4KNaIWZAiWcPf93ibwXiqr9
  APPVEYOR_TOKEN:
    secure: wVt1RgJAnhNTyIjtK9yFkQbEEM+fBk1TLUzo0j3pe2U=
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: false
build_script:
  - ps: .\build.ps1
test: off
